### ISSUE TITLE
依赖版本异常

### ISSUE THREAD

**Issue by lj-michale** [melin/spark-jobserver#1]
![image](https://user-images.githubusercontent.com/22366151/207216234-2d751464-5cea-4410-b524-6b68322b85ae.png)

<dependency>
    <groupId>com.gitee.melin.bee</groupId>
    <artifactId>bee</artifactId>
    <version>${bee.version}</version>
    <exclusions>
        <exclusion>
            <groupId>*</groupId>
            <artifactId>*</artifactId>
        </exclusion>
    </exclusions>
</dependency>

**Comment by melin** [comment]
已经提交到maven 仓库，可能要晚一些才可以下载，或者下载源码编译：https://gitee.com/melin/bee

LJ.Michale ***@***.***> 于2022年12月13日周二 11:04写道：
