### ISSUE TITLE
script/jobserver.sql 的表结构不存在

### ISSUE THREAD

**Issue by niutaofan** [melin/spark-jobserver#2]
请问能提供一下表结构么。邮箱：907678300@qq.com

**Comment by melin** [comment]
mysql 脚本地址：https://github.com/melin/spark-jobserver/blob/master/build/script/jobserver.sql

**Comment by niutaofan** [comment]
> mysql 脚本地址：https://github.com/melin/spark-jobserver/blob/master/build/script/jobserver.sql

感谢

**Comment by melin** [comment]
有部署成功吗？ 有合适使用场景吗？

**Comment by niutaofan** [comment]
在电脑上跑了编译好的生态环境，还在研究阶段😁
