### ISSUE TITLE
当前master 代码缺失？

### ISSUE THREAD

**Issue by donyee** [melin/spark-jobserver#8]
感谢作者开源了这么牛的项目，之前版本我编译部署成功；
目前最新的master 代码发现一些小bug，不能编译成功；
io.github.melin.spark.jobserver.driver.task.SparkStreamSqlTask java 代码有些错误；
import io.github.melin.superior.parser.spark.SparkStreamSQLHelper;--拼写错误，应该是 SparkStreamSqlHelper。
StreamTable 这个类不知道从哪里导入的，最新的 superior-sql-parser 项目中没有找到 StreamTable 。

**Comment by melin** [comment]
重构了代码，你可以看一下TestCase 怎么使用的：SparkStreamSqlParserTest
